// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKSPEc5awUUfeRaYZJnCz-o_VJWrcvT4Q',
    appId: '1:1022625670758:web:f7eee465aeb8a2c291afa7',
    messagingSenderId: '1022625670758',
    projectId: 'nicholaslim',
    authDomain: 'nicholaslim.firebaseapp.com',
    storageBucket: 'nicholaslim.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAMtMsu0BYgNaEpBfUE_bzk-Y6yeClbIM',
    appId: '1:1022625670758:android:bf53fdd6f6d995e591afa7',
    messagingSenderId: '1022625670758',
    projectId: 'nicholaslim',
    storageBucket: 'nicholaslim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApis77c3hBDE4GmeFKrUUyLK7cWTLTzUo',
    appId: '1:1022625670758:ios:7555c389e908911491afa7',
    messagingSenderId: '1022625670758',
    projectId: 'nicholaslim',
    storageBucket: 'nicholaslim.firebasestorage.app',
    iosBundleId: 'com.example.nicholaslim80',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApis77c3hBDE4GmeFKrUUyLK7cWTLTzUo',
    appId: '1:1022625670758:ios:7555c389e908911491afa7',
    messagingSenderId: '1022625670758',
    projectId: 'nicholaslim',
    storageBucket: 'nicholaslim.firebasestorage.app',
    iosBundleId: 'com.example.nicholaslim80',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKSPEc5awUUfeRaYZJnCz-o_VJWrcvT4Q',
    appId: '1:1022625670758:web:bfa36b2a9f1f261991afa7',
    messagingSenderId: '1022625670758',
    projectId: 'nicholaslim',
    authDomain: 'nicholaslim.firebaseapp.com',
    storageBucket: 'nicholaslim.firebasestorage.app',
  );
}
